/* EFS crcker. Hacked together during 2013 monsoons by Dhiru Kholia
 * <dhiru.kholia at gmail.com>.
 *
 * This software is Copyright (c) 2013, Dhiru Kholia <dhiru.kholia at gmail.com>,
 * and it is hereby released to the general public under the following terms:
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted.
 *
 * All credits for the algorithm go to "dpapick" project,
 * https://bitbucket.org/jmichel/dpapick
 *
 * XXX make this generic!
 * Hash Format ==> $efs$SID$iv$iterations$ciphertext
 */

#include <string.h>
#include <assert.h>
#include <errno.h>
#include "arch.h"
#include "misc.h"
#include "common.h"
#include "formats.h"
#include "params.h"
#include "memory.h"
#include "options.h"
#include <openssl/sha.h>
#include "gladman_hmac.h"
#include <openssl/des.h>
#ifdef _OPENMP
#include <omp.h>
#define OMP_SCALE               64
#endif

#define FORMAT_LABEL		"EFS"
#define FORMAT_NAME		""
#define ALGORITHM_NAME		"PBKDF2-SHA1-crap 3DES 32/" ARCH_BITS_STR
#define BENCHMARK_COMMENT	""
#define BENCHMARK_LENGTH	-1
#define BINARY_SIZE		0
#define PLAINTEXT_LENGTH	125
#define SALT_SIZE		sizeof(*cur_salt)
#define MIN_KEYS_PER_CRYPT	1
#define MAX_KEYS_PER_CRYPT	1

static struct fmt_tests efs_tests[] = {
	/* Windows XP, openwall.efs */
	{"$efs$S-1-5-21-1482476501-1659004503-725345543-1003$b3d62a0b06cecc236fe3200460426a13$4000$d3841257348221cd92caf4427a59d785ed1474cab3d0101fc8d37137dbb598ff1fd2455826128b2594b846934c073528f8648d750d3c8e6621e6f706d79b18c22f172c0930d9a934de73ea2eb63b7b44810d332f7d03f14d1c153de16070a5cab9324da87405c1c0", "openwall"},
	/* Windows XP, openwall.efs.2 */
	{"$efs$S-1-5-21-1482476501-1659004503-725345543-1005$c9cbd491f78ea6d512276b33f025bce8$4000$091a13443cfc2ddb16dcf256ab2a6707a27aa22b49a9a9011ebf3bb778d0088c2896de31de67241d91df75306e56f835337c89cfb2f9afa940b4e7e019ead2737145032fac0bb34587a707d42da7e00b72601a730f5c848094d54c47c622e2f8c8d204c80ad061be", "JtRisthebest"},
	{NULL}
};

#ifndef min
#define min( a, b ) ( ((a) < (b)) ? (a) : (b) )
#endif

// XXX this is most likely crap!
static void pbkdf2_sha1_shit(unsigned char *password, size_t plen,
    const unsigned char *salt, size_t slen,
    const unsigned long iteration_count, const unsigned long key_length,
    unsigned char *output)
{
	// Size of the generated digest
	unsigned char md_size = 20;

	unsigned long counter = 1;
	unsigned long generated_key_length = 0;
	unsigned long bytes_to_write = 0;

	while (generated_key_length < key_length) {
		// U1 ends up in md1 and work
		unsigned char c[5];
		unsigned char init[20] = { 0 };
		unsigned char U[20] = { 0 };
		unsigned long ic = 1;

		c[0] = (counter >> 24) & 0xff;
		c[1] = (counter >> 16) & 0xff;
		c[2] = (counter >> 8) & 0xff;
		c[3] = (counter >> 0) & 0xff;

		memcpy(U, salt, slen);
		memcpy(U + slen, c, 4);

		for (ic = 0; ic < iteration_count; ic++) {
			unsigned long i = 0;
			hmac_sha1(password, plen, U, slen + 4, U, 20);
			for (i = 0; i < md_size; i++) {
				U[i] = init[i] = init[i]^ U[i];
			}
		}

		// Copy the generated bytes to the key
		bytes_to_write =
		    min((key_length - generated_key_length), md_size);
		memcpy(output + generated_key_length, U, bytes_to_write);
		generated_key_length += bytes_to_write;
		++counter;
	}
}


#if defined (_OPENMP)
static int omp_t = 1;
#endif
static char (*saved_key)[PLAINTEXT_LENGTH + 1];
static int *cracked;

static struct custom_salt {
	unsigned char salt[32];
	unsigned char iv[16];
	int ivlen;
	int iterations;
	int ctlen;
	unsigned char ct[4096];
	unsigned char SID[2048];
} *cur_salt;

static void init(struct fmt_main *self)
{

#if defined (_OPENMP)
	omp_t = omp_get_max_threads();
	self->params.min_keys_per_crypt *= omp_t;
	omp_t *= OMP_SCALE;
	self->params.max_keys_per_crypt *= omp_t;
#endif
	saved_key = mem_calloc_tiny(sizeof(*saved_key) *
			self->params.max_keys_per_crypt, MEM_ALIGN_WORD);
	cracked = mem_calloc_tiny(sizeof(*cracked) *
			self->params.max_keys_per_crypt, MEM_ALIGN_WORD);
}

// XXX implement me!
static int valid(char *ciphertext, struct fmt_main *self)
{
	if (strncmp(ciphertext,  "$efs$", 5) != 0)
		return 0;
	return 1;
}

// XXX implement me!
static void *get_salt(char *ciphertext)
{
	char *ctcopy = strdup(ciphertext);
	char *keeptr = ctcopy;
	int i;
	char *p;
	int length;
	static struct custom_salt cs;
	ctcopy += 5;	/* skip over "$efs$" */
	p = strtok(ctcopy, "$");
	strncpy((char*)cs.SID, p, 2048);
	p = strtok(NULL, "$");
	length = strlen(p) / 2;
	cs.ivlen = length;

	for (i = 0; i < cs.ivlen; i++)
		cs.iv[i] = atoi16[ARCH_INDEX(p[i * 2])] * 16
			+ atoi16[ARCH_INDEX(p[i * 2 + 1])];
	p = strtok(NULL, "$");
	cs.iterations = atoi(p);

	p = strtok(NULL, "$");
	length = strlen(p) / 2;
	cs.ctlen = length;

	for (i = 0; i < cs.ctlen; i++)
		cs.ct[i] = atoi16[ARCH_INDEX(p[i * 2])] * 16
			+ atoi16[ARCH_INDEX(p[i * 2 + 1])];
	MEM_FREE(keeptr);
	return (void *)&cs;
}


static void set_salt(void *salt)
{
	cur_salt = (struct custom_salt *)salt;
}

// XXX avoid hard-coded sizes!
static int kcdecrypt(unsigned char *key, unsigned char *iv, unsigned char *pwdhash, unsigned char *data)
{
	unsigned char out[4096];
	unsigned char *hmacSalt;
	unsigned char *ourKey;
	unsigned char *hmac;
	unsigned char hmacComputed[20];
	unsigned char encKey[20];

	DES_cblock key1, key2, key3;
	DES_cblock ivec;
	DES_key_schedule ks1, ks2, ks3;
	memset(out, 0, sizeof(out));
	memcpy(key1, key, 8);
	memcpy(key2, key + 8, 8);
	memcpy(key3, key + 16, 8);
	DES_set_key((C_Block *) key1, &ks1);
	DES_set_key((C_Block *) key2, &ks2);
	DES_set_key((C_Block *) key3, &ks3);
	memcpy(ivec, iv, 8);
	DES_ede3_cbc_encrypt(data, out, cur_salt->ctlen, &ks1, &ks2, &ks3, &ivec,  DES_DECRYPT);

	// self.key = cleartxt[-64:]
	// self.hmacSalt = cleartxt[:16]
	// self.hmac = cleartxt[16:16+self.hashAlgo.digestLength]
	// self.hmacComputed = crypto.DPAPIHmac(self.hashAlgo, pwdhash,
	//      self.hmacSalt, self.key)
	// self.decrypted = self.hmac == self.hmacComputed

	ourKey = out + cur_salt->ctlen - 64;
	hmacSalt = out; // 16 bytes
	hmac = out + 16;

	// encKey = hmac.new(pwdhash, hmacSalt, dg).digest()
	hmac_sha1(pwdhash, 32, hmacSalt, 16, encKey, 20);

	// return hmac.new(encKey, value, dg).digest()
	// dump_stuff(key, 64);
	hmac_sha1(encKey, 20, ourKey, 64, hmacComputed, 20);

	// dump_stuff(hmac, 20);
	return memcmp(hmac, hmacComputed, 20);
}


static int crypt_all(int *pcount, struct db_salt *salt)
{
	int count = *pcount;
	int index = 0;
#ifdef _OPENMP
#pragma omp parallel for
	for (index = 0; index < count; index += MAX_KEYS_PER_CRYPT)
#endif
	{
		// def derivePassword(userPwd, userSID, hashAlgo)
		// Computes the encryption key from a user's password
		// return derivePwdHash(hashlib.sha1(userPwd.encode("UTF-16LE")).digest()
		// XXX Use magnum's way!
		// 1. UTL-16 LE encode password + hash it
		unsigned char *password = (unsigned char*)saved_key[index];
		unsigned char passwordBuf[512] = {0};
		int passwordBufSize = strlen((char*)password) * 2;
		int i;
		unsigned char c;
		int position = 0;
		unsigned char out[32];
		unsigned char out2[32];
		unsigned char iv[32];
		SHA_CTX ctx;

		/* convert key to UTF-16LE and hash it */
		for(i = 0; (c = password[i]); i++) {
			passwordBuf[position] = c;
			position += 2;
		}
		SHA1_Init(&ctx);
		// puts((char*)password);
		SHA1_Update(&ctx, passwordBuf, passwordBufSize);
		SHA1_Final(out, &ctx);
		// dump_stuff(out, 20);
		// def derivePwdHash(passwordBuf, userSID, hashAlgo)
		// Computes the encryption key from a user's password hash"""
		// return encKey = hmac.new(passwordBuf, (userSID+"\0").encode("UTF-16LE"), dg).digest()
		// 2. UTL-16 LE encode SID + use in HMAC
		password = cur_salt->SID;
		// puts(password);
		passwordBufSize = strlen((char*)password) * 2 + 2;
		position = 0;
		memset(passwordBuf, 0, 512);
		/* convert key to UTF-16LE and hash it */
		for(i = 0; (c = password[i]); i++) {
			passwordBuf[position] = c;
			position += 2;
		}
		hmac_sha1(out, 20, passwordBuf, passwordBufSize, out2, 20);
		// dump_stuff(out2, 20);
		pbkdf2_sha1_shit(out2, 20, cur_salt->iv, 16, 4000, 32, out);
		// split derived key into "key" and IV
		memcpy(iv, out + 24, 8);
		if(kcdecrypt(out, iv, out2, cur_salt->ct) == 0)
				cracked[index] = 1;
			else
				cracked[index] = 0;
	}
	return count;
}

static int cmp_all(void *binary, int count)
{
	int index;
	for (index = 0; index < count; index++)
		if (cracked[index])
			return 1;
	return 0;
}

static int cmp_one(void *binary, int index)
{
	return cracked[index];
}

static int cmp_exact(char *source, int index)
{
    return 1;
}

static void efs_set_key(char *key, int index)
{
	int saved_key_length = strlen(key);
	if (saved_key_length > PLAINTEXT_LENGTH)
		saved_key_length = PLAINTEXT_LENGTH;
	memcpy(saved_key[index], key, saved_key_length);
	saved_key[index][saved_key_length] = 0;
}

static char *get_key(int index)
{
	return saved_key[index];
}

struct fmt_main fmt_efs = {
	{
		FORMAT_LABEL,
		FORMAT_NAME,
		ALGORITHM_NAME,
		BENCHMARK_COMMENT,
		BENCHMARK_LENGTH,
		PLAINTEXT_LENGTH,
		BINARY_SIZE,
		DEFAULT_ALIGN,
		SALT_SIZE,
		DEFAULT_ALIGN,
		MIN_KEYS_PER_CRYPT,
		MAX_KEYS_PER_CRYPT,
		FMT_CASE | FMT_8_BIT | FMT_OMP | FMT_UNICODE,
		efs_tests
	}, {
		init,
		fmt_default_done,
		fmt_default_reset,
		fmt_default_prepare,
		valid,
		fmt_default_split,
		fmt_default_binary,
		get_salt,
		fmt_default_source,
		{
			fmt_default_binary_hash
		},
		fmt_default_salt_hash,
		set_salt,
		efs_set_key,
		get_key,
		fmt_default_clear_keys,
		crypt_all,
		{
			fmt_default_get_hash
		},
		cmp_all,
		cmp_one,
		cmp_exact
	}
};
