generic: default

help: default

all: default

install: default

default:
	@echo "A normal build is now \"./configure && make\"."
	@echo "For listing legacy builds, use \"make -f Makefile.orig\"."
	@echo "For using legacy Makefile, use \"make -f Makefile.orig <target>\"."
