#
# This is a stub Makefile. If you run ./configure you will get a real one.
#

RM = rm -f

generic: default

help: default

all: default

install: default

default:
	@echo "A normal build is now \"./configure && make -sj4\"."
	@echo
	@exit 1

# Unfortunately these does not work due to the @EXE_EXT@ shite
#clean:
#	$(MAKE) -f Makefile.in $@
#
#distclean:
#	$(MAKE) -f Makefile.in $@

# Better than nothing :-/
clean:
	$(RM) *.o

distclean: clean
