/* Crack pbkdf2_sha1 hashes.
 *
 * This software is Copyright (c) 2013 Dhiru Kholia, and it is hereby released
 * to the general public under the following terms:
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted.
 */

#include <openssl/aes.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <assert.h>
#ifdef _OPENMP
static int omp_t = 1;
#include <omp.h>
#define OMP_SCALE               64
#endif
#include "arch.h"
#include "misc.h"
#include "formats.h"
#include "options.h"
#include "common.h"
#include "unicode.h"
#include "base64.h"
#include "gladman_fileenc.h"
#include "pbkdf2_hmac_sha1.h"
#include "loader.h"

#define FORMAT_LABEL            "PBKDF2-HMAC-SHA1"
#define FORMAT_NAME             ""
#ifdef MMX_COEF
#define ALGORITHM_NAME          "PBKDF2-SHA1 " SHA1_N_STR MMX_TYPE
#else
#define ALGORITHM_NAME          "PBKDF2-SHA1 " "32/" ARCH_BITS_STR
#endif
#define BENCHMARK_COMMENT       ""
#define BENCHMARK_LENGTH        -1
#define BINARY_SIZE             20
#define BINARY_ALIGN            4
#define PLAINTEXT_LENGTH        125
#define SALT_ALIGN              4
#ifdef MMX_COEF
#define MIN_KEYS_PER_CRYPT      SSE_GROUP_SZ_SHA1
#define MAX_KEYS_PER_CRYPT      SSE_GROUP_SZ_SHA1
#else
#define MIN_KEYS_PER_CRYPT      1
#define MAX_KEYS_PER_CRYPT      1
#endif

#define OSALT_LENGTH            70
#define SALT_SIZE               sizeof(struct salt_t)
#define FMT_PREFIX              "$pbkdf2$"

static struct fmt_tests tests[] = {
	// testcases generated by passlib, format: $pbkdf2rounds$salt$checksum
	// salt and checksum are encoded in "adapted base64"
	{"$pbkdf2$60000$pjSmtLbWeo/R.p9zzplzDg$mnX4IGpdu2ZUGYHqLECEjVoB8Sc", "openwall"},
	{"$pbkdf2$60000$hFBqbU2pdc45R.hd611LKQ$w9B9nRbDInwIRpfvqbMzjNUmP.M", "password"},
	{NULL},
};

static struct salt_t {
	uint8_t length;
	uint8_t salt[OSALT_LENGTH];
	uint32_t rounds;
} *cur_salt;

static char (*saved_key)[PLAINTEXT_LENGTH + 1];
static ARCH_WORD_32 (*crypt_out)[BINARY_SIZE / sizeof(ARCH_WORD_32)];

static void init(struct fmt_main *self)
{
#ifdef _OPENMP
	omp_t = omp_get_max_threads();
	self->params.min_keys_per_crypt *= omp_t;
	omp_t *= OMP_SCALE;
	self->params.max_keys_per_crypt *= omp_t;
#endif
	saved_key = mem_calloc_tiny(sizeof(*saved_key) *
			self->params.max_keys_per_crypt, MEM_ALIGN_WORD);
	crypt_out = mem_calloc_tiny(sizeof(*crypt_out) * self->params.max_keys_per_crypt, MEM_ALIGN_WORD);
}

static int isabase64(char a)
{
	int ret = 0;
	if (a >= 'a' && a <= 'z')
		ret = 1;
	if (a >= 'A' && a <= 'Z')
		ret = 1;
	if (a >= '0' && a <= '9')
		ret = 1;
	if (a == '.' || a == '/')
		ret = 1;
	return ret;
}

static int valid(char *ciphertext, struct fmt_main *pFmt)
{
	int saltlen = 0;
	char *p, *c = ciphertext;
	if (strncmp(ciphertext, FMT_PREFIX, strlen(FMT_PREFIX) != 0))
		return 0;
/*	if (strlen(ciphertext) < 44 + strlen(FMT_PREFIX))
		return 0; */
	c += strlen(FMT_PREFIX);
	if (strtol(c, NULL, 10) == 0)
		return 0;

	c = strchr(c, '$');
	if (c == NULL)
		return 0;
	c++;
	p = strchr(c, '$');
	if (p == NULL)
		return 0;
	while (c < p) {
		if (!isabase64(*c++))
			return 0;
		saltlen++;
	}
	saltlen = saltlen * 3 / 4;

	if (saltlen > OSALT_LENGTH)
		return 0;
	c++;

	/* if (strlen(c) != 43)
		return 0; */
	while (*c) {
		if (!isabase64(*c++)) {
			return 0;
		}
	}
	return 1;
}

/* adapted base64 encoding used by passlib - s/./+/ and trim padding */
static void abase64_decode(const char *in, int length, char *out)
{
	int i;
	static char hash[70 + 1];
#ifdef DEBUG
	assert(length <= 70);
	assert(length % 4 != 1);
#endif
	memset(hash, '=', 70);
	memcpy(hash, in, length);
	for (i = 0; i < length; i++)
		if (hash[i] == '.')
			hash[i] = '+';
	switch (length % 4) {
	case 2:
		length += 2;
		break;
	case 3:
		length++;
		break;
	}
	hash[length] = 0;
	base64_decode(hash, length, out);
}

static void *binary(char *ciphertext)
{
	static char ret[256 / 8];
	char *c = ciphertext;
	c += strlen(FMT_PREFIX) + 1;
	c = strchr(c, '$') + 1;
	c = strchr(c, '$') + 1;
	assert(strlen(c) == 27);   // XXX
	abase64_decode(c, 27, ret);
	return ret;
}

static void *get_salt(char *ciphertext)
{
	static struct salt_t salt;
	char *p, *c = ciphertext, *oc;
	c += strlen(FMT_PREFIX);
	salt.rounds = strtol(c, NULL, 10);
	c = strchr(c, '$') + 1;
	p = strchr(c, '$');
	salt.length = 0;
	oc = c;
	while (c++ < p)
		salt.length++;
	abase64_decode(oc, salt.length, (char *)salt.salt);
	salt.length = salt.length * 3 / 4;
	return (void *)&salt;
}

static void set_salt(void *salt)
{
	cur_salt = (struct salt_t *)salt;
}

static void set_key(char *key, int index)
{
	int saved_key_length = strlen(key);
	if (saved_key_length > PLAINTEXT_LENGTH)
		saved_key_length = PLAINTEXT_LENGTH;
	memcpy(saved_key[index], key, saved_key_length);
	saved_key[index][saved_key_length] = 0;
}

static char *get_key(int index)
{
	return saved_key[index];
}

static int get_hash_0(int index) { return crypt_out[index][0] & 0xf; }
static int get_hash_1(int index) { return crypt_out[index][0] & 0xff; }
static int get_hash_2(int index) { return crypt_out[index][0] & 0xfff; }
static int get_hash_3(int index) { return crypt_out[index][0] & 0xffff; }
static int get_hash_4(int index) { return crypt_out[index][0] & 0xfffff; }
static int get_hash_5(int index) { return crypt_out[index][0] & 0xffffff; }
static int get_hash_6(int index) { return crypt_out[index][0] & 0x7ffffff; }

static int crypt_all(int *pcount, struct db_salt *salt)
{
	int count = *pcount;
	int index = 0;
#ifdef _OPENMP
#pragma omp parallel for
	for (index = 0; index < count; index += MAX_KEYS_PER_CRYPT)
#endif
	{
		int i;
		int len[MAX_KEYS_PER_CRYPT];
#ifdef MMX_COEF
		unsigned char *pin[MAX_KEYS_PER_CRYPT], *pout[MAX_KEYS_PER_CRYPT];
		for (i = 0; i < MAX_KEYS_PER_CRYPT; ++i) {
			len[i] = strlen(saved_key[i+index]);
			pin[i] = (unsigned char*)saved_key[i+index];
			pout[i] = (unsigned char *)crypt_out[i];
		}
		pbkdf2_sha1_sse((const unsigned char **)pin, len, cur_salt->salt, 16, cur_salt->rounds, pout, BINARY_SIZE, 0);
#else
		for (i = 0; i < MAX_KEYS_PER_CRYPT; ++i) {
			len[i] = strlen(saved_key[index+i]);
		}
		pbkdf2_sha1((const unsigned char*)saved_key[index], len[0],
		       cur_salt->salt,strlen((char*)cur_salt->salt),
		       cur_salt->rounds, tkey[0], BINARY_SIZE, 0);
#endif
	}
	return count;
}

static int cmp_all(void *binary, int count)
{
	int index = 0;
	for (; index < count; index++)
		if (!memcmp(binary, crypt_out[index], BINARY_SIZE))
			return 1;
	return 0;
}

static int cmp_one(void *binary, int index)
{
	return !memcmp(binary, crypt_out[index], BINARY_SIZE);
}

static int cmp_exact(char *source, int index)
{
	return 1;
}

struct fmt_main fmt_pbkdf2_hmac_sha1 = {
	{
		FORMAT_LABEL,
		FORMAT_NAME,
		ALGORITHM_NAME,
		BENCHMARK_COMMENT,
		BENCHMARK_LENGTH,
		PLAINTEXT_LENGTH,
		BINARY_SIZE,
		BINARY_ALIGN,
		SALT_SIZE,
		SALT_ALIGN,
		MIN_KEYS_PER_CRYPT,
		MAX_KEYS_PER_CRYPT,
		0,
		FMT_CASE | FMT_8_BIT | FMT_OMP,
		tests
	}, {
		init,
		fmt_default_done,
		fmt_default_reset,
		fmt_default_prepare,
		valid,
		fmt_default_split,
		binary,
		get_salt,
		fmt_default_source,
		{
			fmt_default_binary_hash_0,
			fmt_default_binary_hash_1,
			fmt_default_binary_hash_2,
			fmt_default_binary_hash_3,
			fmt_default_binary_hash_4,
			fmt_default_binary_hash_5,
			fmt_default_binary_hash_6
		},
		fmt_default_salt_hash,
		set_salt,
		set_key,
		get_key,
		fmt_default_clear_keys,
		crypt_all,
		{
			get_hash_0,
			get_hash_1,
			get_hash_2,
			get_hash_3,
			get_hash_4,
			get_hash_5,
			get_hash_6
		},
		cmp_all,
		cmp_one,
		cmp_exact
	}
};
